// var storagePath = '/home/deploy/projects/' // git项目拉取到这里
// var deployRootPath = '/usr/share/nginx/html/' // nginx页面目录
// var shellPath = '/home/deploy/shell/' // 脚本存放目录
// var zipPath = '/home/deploy/zip/'
var storagePath = 'D:\\data\\deploy\\projects' // git项目拉取到这里
var deployRootPath = 'D:\\data\\nginx\\html' // nginx页面目录
var shellPath = 'D:\\data\\deploy\\shell' // shell目录
var zipPath = 'D:\\data\\deploy\\zip' // zip目录
module.exports = {storagePath, deployRootPath, shellPath, zipPath}
